generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Role
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          role
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:
        droits: { help: "*  0x001 - modification de l'asso   *  0x002 - gestion des membres   *  0x004 - gestion des articles   *  0x008 - gestion des events   *  0x010 - gestion des roles   *  0x020 - changement de pres   *  0x040 - gestion du materiel   *  0x080 - gestion des mails   *  0x100 - gestion de la trésorerie   *  0x200 - gestion des photos" }
      list:    ~
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
