generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Partenaire
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          partenaire
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title: "Les partenaires"
        display: [nom, position, url, description]
      filter:  
        display: [position] 
      form:    ~
      edit:    ~
      new:     ~
